# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('attributes', jsonfield.fields.JSONField()),
                ('meta_for', models.ManyToManyField(blank=True, to='structure.DocStruct')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('doc_struct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.DocStruct')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('doc_struct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.DocStruct')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer.Layer')),
            ],
        ),
    ]
