# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 22:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_auto_20170909_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
