# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docstruct',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
