version: '3'
services:
  ui:
    image: node:6.11.2
    volumes:
      - $PWD:/usr/src/app
      - libs:/usr/src/app/node_modules/
    working_dir: /usr/src/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    command: .docker/setup_node_then .docker/run_ui.sh
    environment:
      API_BASE: ${API_BASE}
      NODE_ENV: ${NODE_ENV:-dev}
      PORT: 8000

volumes:
  libs:
