# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024)),
                ('tag', models.CharField(max_length=64)),
                ('tag_number', models.CharField(max_length=16)),
                ('marker', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('left', models.PositiveIntegerField()),
                ('right', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_id', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=32)),
                ('doc_subtype', models.CharField(blank=True, max_length=32)),
                ('work_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([('doc_type', 'doc_subtype', 'work_id')]),
        ),
        migrations.AlterIndexTogether(
            name='work',
            index_together=set([('doc_type', 'doc_subtype'), ('doc_type', 'doc_subtype', 'work_id')]),
        ),
        migrations.AddField(
            model_name='expression',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Work'),
        ),
        migrations.AddField(
            model_name='docstruct',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Expression'),
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together=set([('work', 'expression_id', 'author')]),
        ),
        migrations.AlterIndexTogether(
            name='expression',
            index_together=set([('work', 'expression_id', 'author'), ('work', 'expression_id'), ('work', 'date'), ('work', 'date', 'author')]),
        ),
        migrations.AlterUniqueTogether(
            name='docstruct',
            unique_together=set([('expression', 'identifier')]),
        ),
        migrations.AlterIndexTogether(
            name='docstruct',
            index_together=set([('expression', 'right', 'depth'), ('expression', 'left'), ('expression', 'identifier'), ('expression', 'right'), ('expression', 'left', 'depth'), ('expression', 'tag')]),
        ),
    ]
