# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024)),
                ('tag', models.CharField(max_length=64)),
                ('tag_number', models.CharField(max_length=16)),
                ('marker', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('left', models.PositiveIntegerField()),
                ('right', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=32)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, max_length=32)),
                ('doc_subtype', models.CharField(blank=True, max_length=32)),
                ('work_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([('doc_type', 'doc_subtype', 'work_id')]),
        ),
        migrations.AlterIndexTogether(
            name='work',
            index_together=set([('doc_type', 'doc_subtype', 'work_id'), ('doc_type', 'doc_subtype')]),
        ),
        migrations.AddField(
            model_name='entity',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Work'),
        ),
        migrations.AddField(
            model_name='docstruct',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('work', 'entity_id')]),
        ),
        migrations.AlterIndexTogether(
            name='entity',
            index_together=set([('work', 'date'), ('work', 'entity_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='docstruct',
            unique_together=set([('entity', 'identifier')]),
        ),
        migrations.AlterIndexTogether(
            name='docstruct',
            index_together=set([('entity', 'tag'), ('entity', 'left'), ('entity', 'identifier')]),
        ),
    ]
