# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=1024)),
                ('text', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Work'),
        ),
        migrations.AddField(
            model_name='docstruct',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('work', 'identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='docstruct',
            unique_together=set([('entity', 'identifier')]),
        ),
    ]
