# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='name',
        ),
        migrations.AddField(
            model_name='entity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='identifier',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
