# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20170816_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docstruct',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='docstruct',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='docstruct',
            name='path',
        ),
        migrations.AddField(
            model_name='docstruct',
            name='left',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docstruct',
            name='right',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
