#!/bin/bash

set -e

if [ -n "$DEBUG" ]; then
  if [ ! -d .venv-dev/bin ]; then
    python -m venv .venv-dev
  fi
  source .venv-dev/bin/activate
else
  if [ ! -d .venv-prod/bin ]; then
    python -m venv .venv-prod
  fi
  source .venv-prod/bin/activate
fi

if ! [ -x "$(command -v pip-sync)" ]; then
  pip install pip-tools==1.9.0
fi

