version: '3'
services:
  db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data

  api:
    image: python:3.6.2
    volumes:
      - $PWD:/usr/src/app:delegated
      - dev-libs:/usr/src/app/.venv-dev/
      - prod-libs:/usr/src/app/.venv-prod/
    working_dir: /usr/src/app
    ports: 
      - 8001:8001
    stdin_open: true
    tty: true
    command: .docker/setup_python_then .docker/wait_for_db_then .docker/run_api.sh
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      DEBUG: ${DEBUG:-true}
      PORT: 8001
      TMPDIR: /tmp
      VCAP_APPLICATION: >
        {"uris": ["*"]}
    depends_on:
      - db

volumes:
  database_data:
  dev-libs:
  prod-libs:
